import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
// import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Layout from "../components/Layout";

// const geistSans = GeistSans({
//   variable: "--font-geist-sans",
// });

// const geistMono = GeistMono({
//   variable: "--font-geist-mono",
// });

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  variable: "--font-ibm-plex-sans-thai",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["thai", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSansThai.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
